version: '3.7'

services:
  redis:
    image: redis:7.2.5
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin12345
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    command: redis-server --requirepass admin12345
    volumes:
      - ./redis-data/:/root/redis
      - ./redis-data/redis.conf:/usr/local/etc/redis/redis.conf

    backend-app:
      build:
        dockerfile: Dockerfile
        context: ./backend-app
      container_name: backend-app
      ports:
        - "8002:8002"
      restart: always
      depends_on:
        - "kafka-3"
      command:
        - '/bin/sh'
        - '-c'
        - '/bin/sleep 30 && npm run "container"'
      volumes:
        - ./backend-app/:/app/backend-app
        - /app/backend-app/node_modules